Added a grogram for calculating change
Milightning/CS50 pull request #4
Opened 2024-01-29 19:56 UTC by Milightning

Added .gitignore file

'do while' loop checks if the value of the change is more than 0

'while' loops counts the amount of quarters, dimes, nickels and pennies

2024-01-29 20:13 UTC, Shiaulis requested changes
It is a bit better now, but there is one major issue with this PR:
It is super inconvenient to review this code. To ensure it works properly I need:
1. Open CS50 website
2. Find where all problem sets are located
3. Find which problem set you are solving
4. Find what task from problem set you are solving

This could be fixed by simply putting link to the task itself. It is also useful to drop more descriptive information WHAT this code is about. For example:

> This is solution of `Cash` task that was described in problem set 1. This code calculates… etc.

So please:
1. Add a proper description. Github is using markdown so making it pretty and comfortable to read is easy
2. Add all needed links to enable review for this code. You can even share a link to a VSCode so whoever is testing it would be able to test it easily


Keep also in mind that your quotes are not proper markdown quotes so if you leave existing text here, please, ensure, it is using proper markdown syntax

2024-01-29 20:13 UTC, Shiaulis commented on .gitignore
> +.DS_Store
this didn't help since you still have a file in repo. So you need to delete the `.DS_Store` file from repo as well

2024-01-29 20:13 UTC, Shiaulis commented on cash/cash.c
> +        while (change >= 25)
this violates styling requirements from CS50. Please do your changes in VSCode online and then use `style50` and `check50` utilities to ensure your code is 100% valid

2024-01-31 08:57 UTC, Shiaulis approved these changes
Great to see you've fixed most of issues 🚀
Before we merge **please fix the title**, otherwise it will stay there when we merge changes to the main branch.
To simplify process for this and upcoming PRs let's use squash and merge option. What it does, it merges all commits into one and put it as a top commit into main branch. If future it makes sense to try other options but for now this looks the easiest one

<img width="456" alt="image" src="https://github.com/Milightning/CS50/assets/13601748/aab3d466-24f7-46f5-834e-8f378d869d16">

2024-01-31 11:30 UTC, merged

2024-01-31 11:30 UTC, Milightning commented
the title is fixed and the pull request is finally squashed and merged